### ISSUE TITLE
Bot give 404 from admin panel 

### ISSUE THREAD

**Issue by denisgolius** [nixys/nxs-chat-redmine#2]
Bot give 404 from admin panel whet I try ti configure it.

http://i.piccy.info/i9/8b6cf7d1d5a6c6cc1dd6a63b331d293d/1540466085/37395/1277312/FireShot_Capture_026_Ynformatsyia_Redmine_https_redmine_ifs_sumy_ua_admin_info.png

http://i.piccy.info/i9/919ef1ff7ce59d3eba2202f76af7f6a3/1540456033/20966/1277312/FireShot_Capture_022_Moduly_Redmine_https_redmine_ifs_sumy_ua_admin_plugins.png

http://i.piccy.info/i9/8dc0b5b019e5dc52887e5a1366b81ac9/1540456076/14919/1277312/FireShot_Capture_023_404_Redmine_https_redmine_ifs_sumy_ua_settings_plugin_nxs_chat.png

**Comment by borisershov** [comment]
Hi!

Can you provide the Redmine logs related to your actions?

**Comment by denisgolius** [comment]
```
Started GET "/settings/plugin/nxs_chat" for 193.34.x.x at 2018-11-13 15:31:20 +0200
Processing by SettingsController#plugin as HTML
Parameters: {«id»=>«nxs_chat»}
Current user: dengolius (id=6)
Rendered settings/plugin.html.erb within layouts/admin (1.7ms)
Missing template, responding with 404
Rendered common/error.html.erb within layouts/base (0.3ms)
Completed 404 Not Found in 13ms (Views: 5.7ms | ActiveRecord: 2.3ms)```

**Comment by denisgolius** [comment]
Это может быть связано с отсутсвием сертификатов у сервера nxs-chat-srv и вообще его работой?

**Comment by borisershov** [comment]
Очень маловероятно, т.к. при входе в настройки плагина взаимодействия с nxs-chat-srv нет.

Смущает сообщение `Missing template`. Мы тогда посмотрим с чем оно может быть связано и отпишемся.

**Comment by borisershov** [comment]
Проверьте, пожалуйста, в какой именно директории у Вас располагается plugin? Он обязательно должен находиться в директории `REDMINE_PATH/plugins/nxs_chat` в соответствии с [инструкцией по установке](https://github.com/nixys/nxs-chat-redmine#installation).

**Comment by denisgolius** [comment]
```
root@redmine .../redmine/plugins# pwd
/var/www/redmine/plugins
root@redmine .../redmine/plugins# ls -1
README
nxs-chat
redmine_backlogs
redmine_telegram
root@redmine .../redmine/plugins# ll
total 24
drwxrwxr-x  5 www-data www-data 4096 Nov 15 14:41 ./
drwxrwxr-x 18 root     www-data 4096 Oct 19 11:54 ../
-rw-rw-r--  1 www-data www-data   31 Jun 10 09:36 README
drwxr-xr-x  6 www-data www-data 4096 Oct 19 11:39 nxs-chat/
drwxr-xr-x  3 www-data www-data 4096 Jun 14 23:48 redmine_backlogs/
drwxr-xr-x  5 www-data www-data 4096 Sep 19 06:57 redmine_telegram/
root@redmine .../redmine/plugins# 

```

результат тот же - 404

**Comment by denisgolius** [comment]
```
Started GET "/admin/plugins" for some_ip at 2018-11-15 14:44:27 +0200
Processing by AdminController#plugins as HTML
  Current user: dengolius (id=6)
  Rendered admin/plugins.html.erb within layouts/admin (1.1ms)
  Rendered admin/_menu.html.erb (1.3ms)
  Rendered layouts/base.html.erb (4.7ms)
Completed 200 OK in 12ms (Views: 7.8ms | ActiveRecord: 2.6ms)
Started GET "/settings/plugin/nxs_chat" for some_ip at 2018-11-15 14:44:33 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"nxs_chat"}
  Current user: dengolius (id=6)
  Rendered settings/plugin.html.erb within layouts/admin (1.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 15ms (Views: 5.2ms | ActiveRecord: 2.7ms)

```

**Comment by borisershov** [comment]
У Вас имя каталога с плагином не правильное. Должно быть `nxs_chat` вместо `nxs-chat`.
Попробуйте переименовать, пожалуйста.

**Comment by borisershov** [comment]
Полагаю, что задачу можно закрывать.

**Comment by denisgolius** [comment]
менял  имя каталоги, и перекачивал - ничего это не решило... без понятия, почему оно так и не заработало
